FROM archlinux AS builder

COPY bash-5.3.tar.gz /opt 
RUN cd /opt && tar xzf /opt/bash-5.3.tar.gz 

WORKDIR /opt/bash-5.3

RUN yes | pacman -Syu gcc mandoc make groff
RUN ./configure 
RUN make 
RUN mkdir -p /off_path/bin/ && mv /bin/* /off_path/bin/  && /off_path/bin/mv bash /bin/bash && /off_path/bin/ln -s /bin/bash /bin/sh 

RUN /off_path/bin/head -1 /etc/passwd | /off_path/bin/sed 's;/usr/bin;;' >> /tmp/passwd


FROM scratch
USER root
COPY --from=builder /tmp/passwd /etc/passwd 
COPY --from=builder --chmod=755 /bin/bash /bin/bash 
COPY --from=builder --chmod=755 /bin/bash /bin/sh
COPY --from=builder /lib /lib
COPY --from=builder /usr/lib /usr/lib
COPY --from=builder /lib64 /lib64

ENV SHELL=/bin/sh

CMD ["/bin/bash", "-l"]

